baseURL = "https://coxley.org/"
languageCode = "en-us"
title = "coxley"
theme = ["theme"]
googleAnalytics = "UA-164601472-1"

[permalinks]
  post = "/:filename"

[params]
  Subtitle = ""
  GithubID = "coxley"
  AboutURL = "about"
  # NowURL = "now"
  IndexTitle = "Codey Oxley"
  AnalyticsID = "UA-164601472-1"
  mainSections = ["post"]

[markup]
  [markup.highlight]
    tabWidth = 2
